### ISSUE TITLE
Update training to use accessions

### ISSUE THREAD

**Issue by iimog** [iimog/meta-barcoding-dual-indexing#4]
As NCBI has phased out GI numbers and purely uses accessions now, many of the scripts no longer work. Those have to be updated to use accessions instead. This also relies on upstream libraries to be fixed: https://github.com/greatfireball/NCBI-Taxonomy/issues/5

**Comment by boryanakis** [comment]
Hi. I'm running into the same problem. Were you able to come up with a workaround?

**Comment by iimog** [comment]
Hi @boryanakis I have no workaround, yet. I might have an hour to look into it today. Stay tuned. If you come up with anything - let me know.

**Comment by iimog** [comment]
The NCBI-Taxonomy module supports accessions since version 0.9. So updating to that version should fix the problem.
